Repository josephdadams/TallyArbiter, pull requests merged in 2021-08, with the labels that each got.

#138 Osc sourcetype patch
  UI/src/app/_components/settings/settings.component.ts
Labels: bug

#139 Support for rate limiter and brute force protection
  UI/src/app/_components/login/login.component.html
  UI/src/app/_components/login/login.component.ts
  UI/src/app/_services/auth.service.ts
  index.js
  package-lock.json
  package.json
Labels: feature

#166 Adds an "Are you sure you want to quit" prompt to the elctron app
  .DS_Store
  main.js
Labels: feature

#173 device renaming
  UI/src/app/_components/settings/settings.component.html
  UI/src/app/_models/DeviceSource.ts
  index.js
Labels: feature

#183 external Address option
  .DS_Store
  .gitignore
  TallyArbiter.code-workspace
  UI/src/app/_components/home/home.component.html
  UI/src/app/_components/home/home.component.ts
  UI/src/app/_services/socket.service.ts
  index.js
  package-lock.json
Labels: in progress, feature

#184 add support for outgoing TSL UMD 5
  docs/docs/usage/sections/devices.md
  index.js
  package-lock.json
  package.json
Labels: feature

#196 Add "(unread)" near unreaded error reports and add "Mark all as read" and "Delete error reports from disk"
  UI/src/app/_components/error-reports-list/error-reports-list.component.html
  UI/src/app/_components/error-reports-list/error-reports-list.component.scss
  UI/src/app/_components/error-reports-list/error-reports-list.component.ts
  index.js
  package-lock.json
  package.json
Labels: enhancement

#193 Truncate logs and bug title
  .gitignore
  UI/git.version.js
  UI/package.json
  UI/src/app/_components/error-report/error-report.component.html
  UI/src/app/_components/error-report/error-report.component.ts
  UI/src/app/_decorators/confirmable.decorator.ts
Labels: enhancement, in progress
